
import telebot
import json
import random

bot = telebot.TeleBot("7710101379:AAEKHFNlb7kRO-jCfu9agOWKwQZsk8UwNNI")

with open("psalms.json", encoding="utf-8") as f:
    psalms = json.load(f)

with open("calendar.json", encoding="utf-8") as f:
    calendar = json.load(f)

with open("wisdom.json", encoding="utf-8") as f:
    wisdom = json.load(f)

with open("books.json", encoding="utf-8") as f:
    books = json.load(f)

with open("prayers.json", encoding="utf-8") as f:
    prayers = json.load(f)

@bot.message_handler(commands=["start"])
def send_welcome(message):
    markup = telebot.types.ReplyKeyboardMarkup(resize_keyboard=True)
    markup.add("Псалмы", "Молитвы", "Книги")
    markup.add("Календарь", "Мудрость дня")
    bot.send_message(message.chat.id, "Добро пожаловать! Выбери раздел:", reply_markup=markup)

@bot.message_handler(func=lambda m: True)
def menu_handler(message):
    if message.text == "Псалмы":
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Псалом 1", callback_data="psalm_1"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 2", callback_data="psalm_2"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 3", callback_data="psalm_3"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 4", callback_data="psalm_4"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 5", callback_data="psalm_5"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 6", callback_data="psalm_6"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 7", callback_data="psalm_7"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 8", callback_data="psalm_8"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 9", callback_data="psalm_9"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 10", callback_data="psalm_10"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 11", callback_data="psalm_11"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 12", callback_data="psalm_12"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 13", callback_data="psalm_13"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 14", callback_data="psalm_14"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 15", callback_data="psalm_15"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 16", callback_data="psalm_16"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 17", callback_data="psalm_17"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 18", callback_data="psalm_18"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 19", callback_data="psalm_19"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 20", callback_data="psalm_20"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 21", callback_data="psalm_21"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 22", callback_data="psalm_22"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 23", callback_data="psalm_23"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 24", callback_data="psalm_24"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 25", callback_data="psalm_25"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 26", callback_data="psalm_26"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 27", callback_data="psalm_27"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 28", callback_data="psalm_28"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 29", callback_data="psalm_29"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 30", callback_data="psalm_30"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 31", callback_data="psalm_31"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 32", callback_data="psalm_32"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 33", callback_data="psalm_33"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 34", callback_data="psalm_34"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 35", callback_data="psalm_35"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 36", callback_data="psalm_36"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 37", callback_data="psalm_37"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 38", callback_data="psalm_38"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 39", callback_data="psalm_39"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 40", callback_data="psalm_40"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 41", callback_data="psalm_41"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 42", callback_data="psalm_42"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 43", callback_data="psalm_43"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 44", callback_data="psalm_44"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 45", callback_data="psalm_45"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 46", callback_data="psalm_46"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 47", callback_data="psalm_47"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 48", callback_data="psalm_48"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 49", callback_data="psalm_49"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 50", callback_data="psalm_50"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 51", callback_data="psalm_51"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 52", callback_data="psalm_52"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 53", callback_data="psalm_53"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 54", callback_data="psalm_54"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 55", callback_data="psalm_55"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 56", callback_data="psalm_56"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 57", callback_data="psalm_57"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 58", callback_data="psalm_58"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 59", callback_data="psalm_59"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 60", callback_data="psalm_60"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 61", callback_data="psalm_61"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 62", callback_data="psalm_62"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 63", callback_data="psalm_63"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 64", callback_data="psalm_64"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 65", callback_data="psalm_65"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 66", callback_data="psalm_66"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 67", callback_data="psalm_67"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 68", callback_data="psalm_68"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 69", callback_data="psalm_69"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 70", callback_data="psalm_70"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 71", callback_data="psalm_71"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 72", callback_data="psalm_72"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 73", callback_data="psalm_73"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 74", callback_data="psalm_74"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 75", callback_data="psalm_75"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 76", callback_data="psalm_76"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 77", callback_data="psalm_77"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 78", callback_data="psalm_78"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 79", callback_data="psalm_79"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 80", callback_data="psalm_80"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 81", callback_data="psalm_81"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 82", callback_data="psalm_82"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 83", callback_data="psalm_83"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 84", callback_data="psalm_84"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 85", callback_data="psalm_85"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 86", callback_data="psalm_86"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 87", callback_data="psalm_87"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 88", callback_data="psalm_88"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 89", callback_data="psalm_89"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 90", callback_data="psalm_90"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 91", callback_data="psalm_91"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 92", callback_data="psalm_92"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 93", callback_data="psalm_93"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 94", callback_data="psalm_94"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 95", callback_data="psalm_95"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 96", callback_data="psalm_96"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 97", callback_data="psalm_97"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 98", callback_data="psalm_98"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 99", callback_data="psalm_99"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 100", callback_data="psalm_100"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 101", callback_data="psalm_101"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 102", callback_data="psalm_102"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 103", callback_data="psalm_103"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 104", callback_data="psalm_104"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 105", callback_data="psalm_105"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 106", callback_data="psalm_106"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 107", callback_data="psalm_107"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 108", callback_data="psalm_108"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 109", callback_data="psalm_109"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 110", callback_data="psalm_110"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 111", callback_data="psalm_111"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 112", callback_data="psalm_112"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 113", callback_data="psalm_113"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 114", callback_data="psalm_114"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 115", callback_data="psalm_115"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 116", callback_data="psalm_116"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 117", callback_data="psalm_117"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 118", callback_data="psalm_118"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 119", callback_data="psalm_119"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 120", callback_data="psalm_120"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 121", callback_data="psalm_121"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 122", callback_data="psalm_122"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 123", callback_data="psalm_123"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 124", callback_data="psalm_124"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 125", callback_data="psalm_125"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 126", callback_data="psalm_126"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 127", callback_data="psalm_127"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 128", callback_data="psalm_128"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 129", callback_data="psalm_129"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 130", callback_data="psalm_130"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 131", callback_data="psalm_131"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 132", callback_data="psalm_132"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 133", callback_data="psalm_133"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 134", callback_data="psalm_134"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 135", callback_data="psalm_135"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 136", callback_data="psalm_136"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 137", callback_data="psalm_137"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 138", callback_data="psalm_138"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 139", callback_data="psalm_139"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 140", callback_data="psalm_140"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 141", callback_data="psalm_141"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 142", callback_data="psalm_142"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 143", callback_data="psalm_143"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 144", callback_data="psalm_144"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 145", callback_data="psalm_145"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 146", callback_data="psalm_146"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 147", callback_data="psalm_147"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 148", callback_data="psalm_148"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 149", callback_data="psalm_149"))
        markup.add(telebot.types.InlineKeyboardButton("Псалом 150", callback_data="psalm_150"))
        bot.send_message(message.chat.id, "Выбери псалом:", reply_markup=markup)
    elif message.text == "Молитвы":
        for p in prayers:
            text = f"*{p['title']}*\n\n{p['text_he']}\n\n{p['text_ru']}"
            bot.send_message(message.chat.id, text, parse_mode="Markdown")
    elif message.text == "Книги":
        for b in books:
            text = f"*{b['title']}* — {b['author']}\n{b['description']}"
            bot.send_message(message.chat.id, text, parse_mode="Markdown")
    elif message.text == "Календарь":
        for c in calendar:
            text = f"📅 {c['date']} — *{c['event']}*\n{c['description']}"
            bot.send_message(message.chat.id, text, parse_mode="Markdown")
    elif message.text == "Мудрость дня":
        q = random.choice(wisdom)
        bot.send_message(message.chat.id, f"«{q['quote']}»\n— {q['author']}")

@bot.callback_query_handler(func=lambda call: call.data.startswith("psalm_"))
def send_psalm(call):
    num = int(call.data.split("_")[1])
    p = psalms[num - 1]
    text = f"*ПСАЛОМ {p['number']}* / {p['title_he']}\n"            f"**{p['title_ru']}**\n\n"            f"*Иврит:*\n{p['text_he']}\n\n"            f"*Перевод:*\n{p['text_ru']}\n\n"            f"_Комментарий:_ {p['comment']}"
    bot.send_message(call.message.chat.id, text, parse_mode="Markdown")

bot.polling()
